{% set name = "Platypus-Opt" %}

{% set version = "1.1.0" %}
{% set git_rev = "7c6317a073ce3440bfdc5824fed4f7aeec8835a3" %}
{% set build_number = 0 %}
{% set sha256 = "19610123c204e2dfc10741c69403b57a649589d9494de0fce0fc27579e586bbd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - platypus
  requires:
    - mock
    - nose
  source_files:
    - pyproject.toml
    - platypus/*

about:
  home: https://github.com/Project-Platypus/Platypus
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: Multiobjective optimization in Python
  doc_url: http://platypus.readthedocs.org/en/latest/index.html
  dev_url: https://github.com/Project-Platypus/Platypus

extra:
  recipe-maintainers:
    - jetuk
