{% set name = "Platypus-Opt" %}

{% set version = "1.2.0" %}
{% set git_rev = "7c6317a073ce3440bfdc5824fed4f7aeec8835a3" %}
{% set build_number = 0 %}
{% set sha256 = "f7150de2e24f8003c911259c575493c9351a7dcfb132445a3f3b096728634e6a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs platypus

about:
  home: https://github.com/Project-Platypus/Platypus
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Multiobjective optimization in Python
  doc_url: http://platypus.readthedocs.org/en/latest/index.html
  dev_url: https://github.com/Project-Platypus/Platypus

extra:
  recipe-maintainers:
    - jetuk
